Staging
Revature-Cinephiliacs/CinephiliacsRepo pull request #45
Opened 2021-05-03 21:53 UTC by tristyn-l

2021-05-03 22:18 UTC, clarson217 requested changes
There's quite a few methods that need comments, and a few blocks of commented-out code  to be removed

2021-05-03 22:18 UTC, clarson217 commented on src/app/admintools/admintools.component.ts
> +}
Needs comments (probably)

2021-05-03 22:18 UTC, clarson217 commented on src/app/discussion/discussion.component.ts
> +  }
Some methods need comments

2021-05-03 22:18 UTC, clarson217 commented on src/app/error.service.ts
> +
Needs Comments

2021-05-03 22:18 UTC, clarson217 commented on src/app/forum.service.ts
> +}
getDiscussion, getTopics, getUserDiscussions, getUserComments, getUserFollowedDiscussion, postComment, submitDiscussion  need comments

2021-05-03 22:18 UTC, clarson217 commented on src/app/get-started-box/get-started-box.component.scss
> +  //   }
Should remove commented blocks I think.

2021-05-03 22:18 UTC, clarson217 commented on src/app/get-started-box/get-started-box.component.ts
> +}
Comments

2021-05-03 22:18 UTC, clarson217 commented on src/app/home/home.component.ts
> +    });
Comment?

2021-05-03 22:18 UTC, clarson217 commented on src/app/movie-discussions/movie-discussions.component.scss
> +// }
Should remove commented code

2021-05-03 22:18 UTC, clarson217 commented on src/app/movie/movie.component.ts
> +      // });
Remove commented code

2021-05-03 22:18 UTC, clarson217 commented on src/app/movie/movie.component.ts
> +  // }
Remove commented code

2021-05-03 22:18 UTC, clarson217 commented on src/app/profile/profile.component.ts
>  }
Comments

2021-05-03 22:18 UTC, clarson217 commented on src/app/review/review.component.ts
> +    // this.logger.log("", this.sumbitReview);
Remove commented code.

2021-05-03 22:18 UTC, clarson217 commented on src/app/url.service.ts
> +  // FrontendUrl: string = "http://20.94.137.143/";
Should this be taken out?

2021-05-03 22:18 UTC, clarson217 commented on src/app/user.service.ts
>    }
Needs comments

2021-05-04 00:55 UTC, clarson217 approved these changes

2021-05-04 19:47 UTC, markmoorerev approved these changes

2021-05-04 19:47 UTC, merged