adds auth0 authentication for angular
Revature-Cinephiliacs/CinephiliacsRepo pull request #5
Opened 2021-04-27 20:58 UTC by NNKamel

2021-04-27 21:02 UTC, clarson217 approved these changes

2021-04-27 21:02 UTC, clarson217 commented on src/app/auth.service.ts
> +
The commented out code is preparation for future merges.

2021-04-27 21:02 UTC, clarson217 commented on src/app/auth.service.ts
> +
The commented out code is preparation for future merges.

2021-04-27 21:02 UTC, tristyn-l approved these changes

2021-04-28 01:27 UTC, markmoorerev commented on src/app/interceptor.service.ts
> +      console.log("in interceptor: " + reply);
any console.log()'s need to be taken out for the production version.

2021-04-28 01:29 UTC, markmoorerev requested changes
change console.log()'s to logging statements.

2021-04-28 20:38 UTC, closed without merging